name: Playwright BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          # Remove cache to avoid lock file error
      
      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps
      
      - name: Create required directories
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/videos
          mkdir -p allure-results
      
      - name: Run tests with Allure reporting
        run: |
          npm run prepare:allure
          npx cucumber-js || true
      
      - name: Generate Allure report
        run: |
          node src/utils/cucumber-allure-adapter.js
          node src/utils/run-allure-report.js
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results
            allure-results
            allure-report
          retention-days: 7
      
      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report 