name: Playwright BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent stuck jobs
    permissions:
      contents: write
      pages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install npm dependencies only
        run: npm install --ignore-scripts --no-package-lock
        timeout-minutes: 5
      
      - name: Install minimal browser
        run: npx playwright install chromium --with-deps
        timeout-minutes: 3
      
      - name: Create required directories
        run: |
          mkdir -p test-results/screenshots
          mkdir -p test-results/videos
          mkdir -p allure-results
      
      - name: Run tests with Allure reporting
        run: |
          npm run prepare:allure
          npx cucumber-js || true
        timeout-minutes: 5
      
      - name: Generate Allure report (without server)
        run: |
          # Generate adapter without browser opening
          node src/utils/cucumber-allure-adapter.js || true
          
          # Just generate the report without starting server
          echo "Generating Allure report without starting server..."
          npx allure generate allure-results -o allure-report --clean
        timeout-minutes: 2
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results
            allure-results
            allure-report
          retention-days: 7
      
      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report 